spring:
  application:
    name: books-api-demo
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: kcb-book
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

p11:
  masking:
    enabled: true
    fields:
      - email
      - phoneNumber
    mask-style: PARTIAL
    mask-character: "*"

